# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.0
_src_path: git@github.com:odoo-ps/psbe-ps-tech-tools.git
include_prettierxml: true
include_ruff_format: true
odoo_version: 17.0
